name: filebot
on:
  repository_dispatch:
    types: ServerStart
  workflow_dispatch:
    
jobs:
  StartServer:
    runs-on: ubuntu-latest
    name: FileBot
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Emby Install
        run: |
          cd /home/runner/
          sudo wget https://github.com/crypt-bphc/filebot/raw/main/FileBot.jar
          sudo java -jar FileBot.jar -help
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONFIG }}
          EOF
          cd /home/runner/
          mkdir Mount
          cd ../../..
          sudo rclone mount Media: /home/runner/Mount --allow-non-empty --daemon --allow-other --cache-db-purge --buffer-size 32M --use-mmap --dir-cache-time 4h --drive-chunk-size 16M  --timeout 1h  --vfs-cache-mode minimal --vfs-read-chunk-size 128M --vfs-read-chunk-size-limit 1G --fast-list
          cd /home/runner/
          sudo java -jar FileBot.jar -script fn:amc --output "/home/mount/MediaServer" --action move -non-strict "/home/mount/Downloads" --log-file amc.log --def excludeList=exclude.txt --def clean=y --def unsorted=y --def movieFormat="/home/mount/MediaServer/{plex.dir}/{fn}" seriesFormat="/home/mount/MediaServer/{plex.dir}/{fn}" animeFormat="/home/mount/MediaServer/{plex.dir}/{fn}}" musicFormat="/home/mount/MediaServer/{plex.dir}/{fn}"
