name: filebot
on:
  repository_dispatch:
    types: ServerStart
  workflow_dispatch:
    
jobs:
  StartServer:
    runs-on: ubuntu-latest
    name: FileBot
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Emby Install
        run: |
          sudo wget https://github.com/crypt-bphc/filebot/raw/main/FileBot.jar
          sudo java -jar FileBot.jar -help
          
